openapi: 3.0.1
info:
  title: Service
  version: 1.0.0
paths:
  /hello-abacate:
    get:
      tags: []
      summary: oi
      description: Manda um oi ao usuário e o mostra links úteis
      operationId: hello
      security:
        - microservice_auth: [ read ]
      responses:
        "200":
          description: Movimento incluido com sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Hello"
components:
  securitySchemes:
    microservice_auth:
      type: "oauth2"
      flows:
        clientCredentials:
          tokenUrl: "/proxy/oauth/token"
          scopes:
            read: Permite ler dados
            write: Permite alterar dados

  schemas:
    Hello:
      type: object
      properties:
        mensagem:
          type: string